"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

interface DownloadImage {
  id: string;
  url: string;
  style: string;
  uploadIndex: number;
}

interface DownloadData {
  orderId: string;
  images: DownloadImage[];
  expiresAt: string;
}

export default function DownloadPage() {
  const params = useParams();
  const token = params.token as string;
  const [data, setData] = useState<DownloadData | null>(null);
  const [error, setError] = useState("");
  const [zipping, setZipping] = useState(false);
  const [activeTab, setActiveTab] = useState(0);

  useEffect(() => {
    fetch(`/api/download/${token}`)
      .then((r) => r.json())
      .then((json) => {
        if (json.error) setError(json.error);
        else setData(json);
      })
      .catch(() => setError("Failed to load images"));
  }, [token]);

  const downloadAll = async () => {
    if (!data) return;
    setZipping(true);
    try {
      const a = document.createElement("a");
      a.href = `/api/download/${token}?zip=1`;
      a.download = "bgswap-photos.zip";
      a.click();
    } catch {
      alert("Failed to download ZIP. Try downloading individually.");
    }
    setZipping(false);
  };

  if (error) {
    return (
      <main className="max-w-2xl mx-auto px-4 py-20 text-center">
        <h1 className="text-2xl font-bold mb-4 text-red-600">{error}</h1>
        <a href="/" className="text-blue-600 underline">Back to home</a>
      </main>
    );
  }

  if (!data) {
    return (
      <main className="max-w-2xl mx-auto px-4 py-20 text-center animate-pulse">
        <div className="text-xl">Loading your photos...</div>
      </main>
    );
  }

  // Group images by upload index
  const grouped: Record<number, DownloadImage[]> = {};
  for (const img of data.images) {
    const idx = img.uploadIndex ?? 0;
    if (!grouped[idx]) grouped[idx] = [];
    grouped[idx].push(img);
  }
  const productTabs = Object.keys(grouped).map(Number).sort((a, b) => a - b);
  const currentImages = grouped[productTabs[activeTab]] || data.images;

  return (
    <main className="max-w-4xl mx-auto px-4 py-12">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">Your Product Photos</h1>
          <p className="text-gray-600">
            {data.images.length} photos{productTabs.length > 1 ? ` across ${productTabs.length} products` : ""}.
            Expires {new Date(data.expiresAt).toLocaleDateString()}.
          </p>
        </div>
        <button
          onClick={downloadAll}
          disabled={zipping}
          className="bg-blue-600 text-white font-semibold px-6 py-3 rounded-lg hover:bg-blue-700 transition disabled:opacity-50"
        >
          {zipping ? "Creating ZIP..." : "Download All (ZIP)"}
        </button>
      </div>

      {/* Product tabs */}
      {productTabs.length > 1 && (
        <div className="flex gap-2 mb-6 overflow-x-auto">
          {productTabs.map((idx, i) => (
            <button
              key={idx}
              onClick={() => setActiveTab(i)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition whitespace-nowrap ${
                i === activeTab
                  ? "bg-blue-600 text-white"
                  : "bg-gray-100 text-gray-600 hover:bg-gray-200"
              }`}
            >
              Product {idx + 1}
            </button>
          ))}
        </div>
      )}

      {/* Image grid */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
        {currentImages.map((img) => (
          <div key={img.id} className="group relative">
            <img
              src={img.url}
              alt={`Product ${(productTabs[activeTab] ?? 0) + 1} — ${img.style} background`}
              className="w-full aspect-square object-cover rounded-lg shadow border border-gray-100"
            />
            <div className="text-center text-xs text-gray-500 mt-1 capitalize">{img.style}</div>
            <a
              href={img.url}
              download={`bgswap-product-${(productTabs[activeTab] ?? 0) + 1}-${img.style}.jpg`}
              className="absolute inset-0 bg-black/50 text-white flex items-center justify-center rounded-lg opacity-0 group-hover:opacity-100 transition font-medium text-sm"
            >
              Download
            </a>
          </div>
        ))}
      </div>

      <p className="text-sm text-gray-500 text-center mt-8">
        These images were generated by AI. All images are yours for personal and commercial use.
      </p>
    </main>
  );
}
